package by.gurinovich.PricePodschet.utils.cargo;

public enum CargoActions {
    CARGOTYPE_BOX_S,CARGOTYPE_BOX_M,CARGOTYPE_BOX_L, CARGOTYPE_BOX_XL,CARGOTYPE_DOCUMENT,CARGOTYPE_ANOTHER, CARGOTYPE_COMMENT,CARGOTYPE_SKIP_COMMENT, CARGOTYPE_CONFIRMATION, CARGOTYPE_DECLINE
}
