package by.gurinovich.PricePodschet.utils.individual;

public enum IndividualActions {
    INDIVIDUALTYPE_ROUTE, INDIVIDUALTYPE_COMMENT, INDIVIDUALTYPE_SKIP_COMMENT, INDIVIDUALTYPE_CONFIRMATION, INDIVIDUALTYPE_DECLINE, INDIVIDUALTYPE_APPLY_OWNER, INDIVIDUALTYPE_DECLINE_OWNER,
}
