package by.gurinovich.PricePodschet.utils.passengers;

public enum PassengerActions {
    PASSENGERTYPE_ROUTE, PASSENGERTYPE_COMMENT, PASSENGERTYPE_SKIP_COMMENT, PASSENGERTYPE_CONFIRMATION, PASSENGERTYPE_DECLINE, PASSENGERTYPE_LIST_OF_CITIES
}
