package by.gurinovich.PricePodschet.utils.states;

public enum BotState {
    START, CARGO_ORDER, CARGO_ORDER_ANOTHER, PASSENGER_ORDER, INDIVIDUAL_ORDER, CARGO_ORDER_ROUTE, PASSENGER_ORDER_ROUTE, INDIVIDUAL_ORDER_ROUTE, CONFIRMATION, SEND_MESSAGE
}
